// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Esfa.Roatp.Register.DeploymentTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RoatpRegisterCsv")]
    [NUnit.Framework.CategoryAttribute("RoatpRegisterCsvTests")]
    public partial class RoatpRegisterCsvFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RoatpRegisterCsv.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RoatpRegisterCsv", "\tAs a user\r\n\tI would like to download a roatp register in csv format", ProgrammingLanguage.CSharp, new string[] {
                        "RoatpRegisterCsvTests"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All link on Roatp Register Page should be accessible")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void AllLinkOnRoatpRegisterPageShouldBeAccessible()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All link on Roatp Register Page should be accessible", new string[] {
                        "Ignore"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
testRunner.Given("I can open roatp website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
testRunner.Then("All links should be accessible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Roatp Register csv file should contain below Columns")]
        public virtual void RoatpRegisterCsvFileShouldContainBelowColumns()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Roatp Register csv file should contain below Columns", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
testRunner.Given("I can open roatp website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
testRunner.When("I request for SFA Roatp csv file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Columns"});
            table1.AddRow(new string[] {
                        "Ukprn"});
            table1.AddRow(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "ProviderType"});
            table1.AddRow(new string[] {
                        "ParentCompanyGuarantee"});
            table1.AddRow(new string[] {
                        "NewOrganisationWithoutFinancialTrackRecord"});
            table1.AddRow(new string[] {
                        "StartDate"});
#line 17
testRunner.Then("I should have a csv file with below columns", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Roatp Register csv file should contain below Ukprn")]
        public virtual void RoatpRegisterCsvFileShouldContainBelowUkprn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Roatp Register csv file should contain below Ukprn", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
testRunner.Given("I can open roatp website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
testRunner.When("I request for SFA Roatp csv file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
testRunner.Then("I should have a csv file with more than 5 Kb contents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN"});
            table2.AddRow(new string[] {
                        "10001446"});
            table2.AddRow(new string[] {
                        "10002107"});
            table2.AddRow(new string[] {
                        "10004736"});
            table2.AddRow(new string[] {
                        "10003231"});
            table2.AddRow(new string[] {
                        "10022237"});
            table2.AddRow(new string[] {
                        "10029699"});
            table2.AddRow(new string[] {
                        "10049460"});
            table2.AddRow(new string[] {
                        "10018361"});
            table2.AddRow(new string[] {
                        "10001947"});
            table2.AddRow(new string[] {
                        "10027146"});
            table2.AddRow(new string[] {
                        "10009206"});
            table2.AddRow(new string[] {
                        "10002140"});
            table2.AddRow(new string[] {
                        "10040909"});
            table2.AddRow(new string[] {
                        "10026238"});
            table2.AddRow(new string[] {
                        "10030120"});
            table2.AddRow(new string[] {
                        "10048326"});
            table2.AddRow(new string[] {
                        "10034336"});
            table2.AddRow(new string[] {
                        "10034015"});
            table2.AddRow(new string[] {
                        "10004434"});
            table2.AddRow(new string[] {
                        "10019278"});
            table2.AddRow(new string[] {
                        "10021585"});
            table2.AddRow(new string[] {
                        "10044749"});
            table2.AddRow(new string[] {
                        "10022283"});
            table2.AddRow(new string[] {
                        "10004013"});
            table2.AddRow(new string[] {
                        "10046979"});
            table2.AddRow(new string[] {
                        "10028238"});
            table2.AddRow(new string[] {
                        "10010672"});
            table2.AddRow(new string[] {
                        "10038165"});
            table2.AddRow(new string[] {
                        "10031126"});
            table2.AddRow(new string[] {
                        "10034310"});
            table2.AddRow(new string[] {
                        "10061102"});
            table2.AddRow(new string[] {
                        "10061462"});
            table2.AddRow(new string[] {
                        "10028269"});
            table2.AddRow(new string[] {
                        "10019646"});
            table2.AddRow(new string[] {
                        "10000061"});
            table2.AddRow(new string[] {
                        "10046006"});
            table2.AddRow(new string[] {
                        "10033736"});
            table2.AddRow(new string[] {
                        "10053076"});
            table2.AddRow(new string[] {
                        "10000080"});
            table2.AddRow(new string[] {
                        "10000137"});
            table2.AddRow(new string[] {
                        "10028693"});
            table2.AddRow(new string[] {
                        "10043565"});
            table2.AddRow(new string[] {
                        "10063434"});
            table2.AddRow(new string[] {
                        "10048865"});
            table2.AddRow(new string[] {
                        "10042119"});
            table2.AddRow(new string[] {
                        "10047241"});
            table2.AddRow(new string[] {
                        "10015933"});
            table2.AddRow(new string[] {
                        "10061684"});
            table2.AddRow(new string[] {
                        "10027693"});
            table2.AddRow(new string[] {
                        "10054692"});
            table2.AddRow(new string[] {
                        "10062656"});
            table2.AddRow(new string[] {
                        "10040684"});
            table2.AddRow(new string[] {
                        "10040513"});
            table2.AddRow(new string[] {
                        "10005451"});
            table2.AddRow(new string[] {
                        "10056190"});
            table2.AddRow(new string[] {
                        "10038201"});
            table2.AddRow(new string[] {
                        "10062108"});
            table2.AddRow(new string[] {
                        "10055355"});
            table2.AddRow(new string[] {
                        "10049099"});
            table2.AddRow(new string[] {
                        "10045007"});
            table2.AddRow(new string[] {
                        "10040809"});
            table2.AddRow(new string[] {
                        "10033536"});
            table2.AddRow(new string[] {
                        "10043832"});
            table2.AddRow(new string[] {
                        "10056690"});
            table2.AddRow(new string[] {
                        "10003979"});
            table2.AddRow(new string[] {
                        "10043253"});
            table2.AddRow(new string[] {
                        "10002500"});
            table2.AddRow(new string[] {
                        "10000498"});
            table2.AddRow(new string[] {
                        "10039013"});
            table2.AddRow(new string[] {
                        "10046413"});
            table2.AddRow(new string[] {
                        "10063578"});
            table2.AddRow(new string[] {
                        "10046797"});
            table2.AddRow(new string[] {
                        "10045359"});
            table2.AddRow(new string[] {
                        "10000654"});
            table2.AddRow(new string[] {
                        "10000670"});
            table2.AddRow(new string[] {
                        "10045450"});
            table2.AddRow(new string[] {
                        "10019630"});
            table2.AddRow(new string[] {
                        "10002073"});
            table2.AddRow(new string[] {
                        "10007140"});
            table2.AddRow(new string[] {
                        "10006442"});
            table2.AddRow(new string[] {
                        "10062918"});
            table2.AddRow(new string[] {
                        "10033140"});
            table2.AddRow(new string[] {
                        "10024790"});
            table2.AddRow(new string[] {
                        "10032053"});
            table2.AddRow(new string[] {
                        "10061599"});
            table2.AddRow(new string[] {
                        "10032663"});
            table2.AddRow(new string[] {
                        "10000794"});
            table2.AddRow(new string[] {
                        "10044607"});
            table2.AddRow(new string[] {
                        "10037391"});
            table2.AddRow(new string[] {
                        "10000820"});
            table2.AddRow(new string[] {
                        "10000824"});
            table2.AddRow(new string[] {
                        "10029952"});
            table2.AddRow(new string[] {
                        "10008119"});
            table2.AddRow(new string[] {
                        "10037375"});
            table2.AddRow(new string[] {
                        "10000919"});
            table2.AddRow(new string[] {
                        "10044664"});
            table2.AddRow(new string[] {
                        "10021602"});
            table2.AddRow(new string[] {
                        "10063306"});
            table2.AddRow(new string[] {
                        "10048409"});
            table2.AddRow(new string[] {
                        "10061581"});
            table2.AddRow(new string[] {
                        "10043062"});
            table2.AddRow(new string[] {
                        "10019065"});
            table2.AddRow(new string[] {
                        "10055749"});
            table2.AddRow(new string[] {
                        "10036130"});
            table2.AddRow(new string[] {
                        "10001123"});
            table2.AddRow(new string[] {
                        "10024015"});
            table2.AddRow(new string[] {
                        "10038922"});
            table2.AddRow(new string[] {
                        "10053618"});
            table2.AddRow(new string[] {
                        "10056862"});
            table2.AddRow(new string[] {
                        "10009326"});
            table2.AddRow(new string[] {
                        "10047322"});
            table2.AddRow(new string[] {
                        "10039527"});
            table2.AddRow(new string[] {
                        "10008152"});
            table2.AddRow(new string[] {
                        "10062100"});
            table2.AddRow(new string[] {
                        "10037364"});
            table2.AddRow(new string[] {
                        "10002061"});
            table2.AddRow(new string[] {
                        "10035614"});
            table2.AddRow(new string[] {
                        "10062798"});
            table2.AddRow(new string[] {
                        "10062046"});
            table2.AddRow(new string[] {
                        "10062343"});
            table2.AddRow(new string[] {
                        "10023993"});
            table2.AddRow(new string[] {
                        "10045070"});
            table2.AddRow(new string[] {
                        "10055423"});
            table2.AddRow(new string[] {
                        "10024320"});
            table2.AddRow(new string[] {
                        "10013392"});
            table2.AddRow(new string[] {
                        "10063574"});
            table2.AddRow(new string[] {
                        "10063444"});
            table2.AddRow(new string[] {
                        "10001458"});
            table2.AddRow(new string[] {
                        "10040196"});
            table2.AddRow(new string[] {
                        "10001477"});
            table2.AddRow(new string[] {
                        "10061921"});
            table2.AddRow(new string[] {
                        "10055883"});
            table2.AddRow(new string[] {
                        "10001079"});
            table2.AddRow(new string[] {
                        "10001531"});
            table2.AddRow(new string[] {
                        "10041952"});
            table2.AddRow(new string[] {
                        "10029683"});
            table2.AddRow(new string[] {
                        "10061865"});
            table2.AddRow(new string[] {
                        "10033547"});
            table2.AddRow(new string[] {
                        "10037751"});
            table2.AddRow(new string[] {
                        "10040208"});
            table2.AddRow(new string[] {
                        "10061407"});
            table2.AddRow(new string[] {
                        "10033408"});
            table2.AddRow(new string[] {
                        "10046078"});
            table2.AddRow(new string[] {
                        "10062110"});
            table2.AddRow(new string[] {
                        "10010077"});
            table2.AddRow(new string[] {
                        "10018992"});
            table2.AddRow(new string[] {
                        "10034952"});
            table2.AddRow(new string[] {
                        "10001778"});
            table2.AddRow(new string[] {
                        "10056711"});
            table2.AddRow(new string[] {
                        "10001786"});
            table2.AddRow(new string[] {
                        "10054677"});
            table2.AddRow(new string[] {
                        "10052892"});
            table2.AddRow(new string[] {
                        "10001828"});
            table2.AddRow(new string[] {
                        "10030571"});
            table2.AddRow(new string[] {
                        "10061490"});
            table2.AddRow(new string[] {
                        "10053799"});
            table2.AddRow(new string[] {
                        "10061640"});
            table2.AddRow(new string[] {
                        "10019901"});
            table2.AddRow(new string[] {
                        "10055832"});
            table2.AddRow(new string[] {
                        "10035789"});
            table2.AddRow(new string[] {
                        "10037969"});
            table2.AddRow(new string[] {
                        "10045268"});
            table2.AddRow(new string[] {
                        "10001967"});
            table2.AddRow(new string[] {
                        "10054816"});
            table2.AddRow(new string[] {
                        "10002009"});
            table2.AddRow(new string[] {
                        "10002054"});
            table2.AddRow(new string[] {
                        "10031161"});
            table2.AddRow(new string[] {
                        "10028038"});
            table2.AddRow(new string[] {
                        "10032448"});
            table2.AddRow(new string[] {
                        "10061540"});
            table2.AddRow(new string[] {
                        "10063298"});
            table2.AddRow(new string[] {
                        "10056731"});
            table2.AddRow(new string[] {
                        "10007823"});
            table2.AddRow(new string[] {
                        "10005310"});
            table2.AddRow(new string[] {
                        "10002187"});
            table2.AddRow(new string[] {
                        "10057175"});
            table2.AddRow(new string[] {
                        "10026843"});
            table2.AddRow(new string[] {
                        "10002226"});
            table2.AddRow(new string[] {
                        "10041891"});
            table2.AddRow(new string[] {
                        "10047290"});
            table2.AddRow(new string[] {
                        "10019041"});
            table2.AddRow(new string[] {
                        "10042906"});
            table2.AddRow(new string[] {
                        "10063513"});
            table2.AddRow(new string[] {
                        "10061473"});
            table2.AddRow(new string[] {
                        "10002078"});
            table2.AddRow(new string[] {
                        "10043814"});
            table2.AddRow(new string[] {
                        "10046403"});
            table2.AddRow(new string[] {
                        "10041069"});
            table2.AddRow(new string[] {
                        "10056710"});
            table2.AddRow(new string[] {
                        "10032788"});
            table2.AddRow(new string[] {
                        "10036549"});
            table2.AddRow(new string[] {
                        "10032081"});
            table2.AddRow(new string[] {
                        "10049450"});
            table2.AddRow(new string[] {
                        "10018277"});
            table2.AddRow(new string[] {
                        "10036581"});
            table2.AddRow(new string[] {
                        "10044025"});
            table2.AddRow(new string[] {
                        "10036202"});
            table2.AddRow(new string[] {
                        "10041505"});
            table2.AddRow(new string[] {
                        "10038291"});
            table2.AddRow(new string[] {
                        "10030935"});
            table2.AddRow(new string[] {
                        "10045798"});
            table2.AddRow(new string[] {
                        "10061808"});
            table2.AddRow(new string[] {
                        "10047090"});
            table2.AddRow(new string[] {
                        "10002599"});
            table2.AddRow(new string[] {
                        "10002608"});
            table2.AddRow(new string[] {
                        "10024751"});
            table2.AddRow(new string[] {
                        "10005728"});
            table2.AddRow(new string[] {
                        "10061399"});
            table2.AddRow(new string[] {
                        "10062142"});
            table2.AddRow(new string[] {
                        "10011056"});
            table2.AddRow(new string[] {
                        "10039882"});
            table2.AddRow(new string[] {
                        "10063272"});
            table2.AddRow(new string[] {
                        "10043571"});
            table2.AddRow(new string[] {
                        "10062797"});
            table2.AddRow(new string[] {
                        "10054069"});
            table2.AddRow(new string[] {
                        "10021347"});
            table2.AddRow(new string[] {
                        "10002767"});
            table2.AddRow(new string[] {
                        "10026002"});
            table2.AddRow(new string[] {
                        "10021650"});
            table2.AddRow(new string[] {
                        "10042662"});
            table2.AddRow(new string[] {
                        "10002801"});
            table2.AddRow(new string[] {
                        "10002803"});
            table2.AddRow(new string[] {
                        "10063274"});
            table2.AddRow(new string[] {
                        "10011147"});
            table2.AddRow(new string[] {
                        "10002852"});
            table2.AddRow(new string[] {
                        "10002917"});
            table2.AddRow(new string[] {
                        "10062703"});
            table2.AddRow(new string[] {
                        "10002929"});
            table2.AddRow(new string[] {
                        "10019650"});
            table2.AddRow(new string[] {
                        "10041332"});
            table2.AddRow(new string[] {
                        "10053682"});
            table2.AddRow(new string[] {
                        "10003010"});
            table2.AddRow(new string[] {
                        "10037360"});
            table2.AddRow(new string[] {
                        "10003088"});
            table2.AddRow(new string[] {
                        "10046346"});
            table2.AddRow(new string[] {
                        "10063510"});
            table2.AddRow(new string[] {
                        "10003165"});
            table2.AddRow(new string[] {
                        "10055777"});
            table2.AddRow(new string[] {
                        "10048055"});
            table2.AddRow(new string[] {
                        "10003193"});
            table2.AddRow(new string[] {
                        "10054792"});
            table2.AddRow(new string[] {
                        "10038232"});
            table2.AddRow(new string[] {
                        "10056904"});
            table2.AddRow(new string[] {
                        "10023326"});
            table2.AddRow(new string[] {
                        "10003270"});
            table2.AddRow(new string[] {
                        "10003289"});
            table2.AddRow(new string[] {
                        "10045258"});
            table2.AddRow(new string[] {
                        "10044103"});
            table2.AddRow(new string[] {
                        "10042894"});
            table2.AddRow(new string[] {
                        "10062713"});
            table2.AddRow(new string[] {
                        "10062322"});
            table2.AddRow(new string[] {
                        "10003354"});
            table2.AddRow(new string[] {
                        "10013539"});
            table2.AddRow(new string[] {
                        "10010213"});
            table2.AddRow(new string[] {
                        "10003380"});
            table2.AddRow(new string[] {
                        "10042114"});
            table2.AddRow(new string[] {
                        "10003430"});
            table2.AddRow(new string[] {
                        "10001156"});
            table2.AddRow(new string[] {
                        "10057945"});
            table2.AddRow(new string[] {
                        "10025726"});
            table2.AddRow(new string[] {
                        "10027564"});
            table2.AddRow(new string[] {
                        "10045776"});
            table2.AddRow(new string[] {
                        "10039151"});
            table2.AddRow(new string[] {
                        "10028542"});
            table2.AddRow(new string[] {
                        "10049153"});
            table2.AddRow(new string[] {
                        "10054760"});
            table2.AddRow(new string[] {
                        "10031812"});
            table2.AddRow(new string[] {
                        "10063435"});
            table2.AddRow(new string[] {
                        "10033723"});
            table2.AddRow(new string[] {
                        "10003566"});
            table2.AddRow(new string[] {
                        "10012766"});
            table2.AddRow(new string[] {
                        "10024415"});
            table2.AddRow(new string[] {
                        "10056750"});
            table2.AddRow(new string[] {
                        "10038982"});
            table2.AddRow(new string[] {
                        "10061591"});
            table2.AddRow(new string[] {
                        "10062635"});
            table2.AddRow(new string[] {
                        "10057058"});
            table2.AddRow(new string[] {
                        "10057290"});
            table2.AddRow(new string[] {
                        "10059947"});
            table2.AddRow(new string[] {
                        "10057497"});
            table2.AddRow(new string[] {
                        "10039264"});
            table2.AddRow(new string[] {
                        "10040240"});
            table2.AddRow(new string[] {
                        "10062958"});
            table2.AddRow(new string[] {
                        "10047966"});
            table2.AddRow(new string[] {
                        "10028279"});
            table2.AddRow(new string[] {
                        "10037250"});
            table2.AddRow(new string[] {
                        "10036006"});
            table2.AddRow(new string[] {
                        "10053869"});
            table2.AddRow(new string[] {
                        "10003954"});
            table2.AddRow(new string[] {
                        "10040426"});
            table2.AddRow(new string[] {
                        "10041881"});
            table2.AddRow(new string[] {
                        "10003981"});
            table2.AddRow(new string[] {
                        "10007769"});
            table2.AddRow(new string[] {
                        "10057010"});
            table2.AddRow(new string[] {
                        "10045909"});
            table2.AddRow(new string[] {
                        "10043813"});
            table2.AddRow(new string[] {
                        "10027374"});
            table2.AddRow(new string[] {
                        "10055021"});
            table2.AddRow(new string[] {
                        "10009491"});
            table2.AddRow(new string[] {
                        "10039481"});
            table2.AddRow(new string[] {
                        "10058123"});
            table2.AddRow(new string[] {
                        "10039744"});
            table2.AddRow(new string[] {
                        "10013073"});
            table2.AddRow(new string[] {
                        "10054499"});
            table2.AddRow(new string[] {
                        "10004140"});
            table2.AddRow(new string[] {
                        "10025823"});
            table2.AddRow(new string[] {
                        "10003996"});
            table2.AddRow(new string[] {
                        "10004343"});
            table2.AddRow(new string[] {
                        "10004351"});
            table2.AddRow(new string[] {
                        "10039512"});
            table2.AddRow(new string[] {
                        "10005264"});
            table2.AddRow(new string[] {
                        "10027518"});
            table2.AddRow(new string[] {
                        "10004376"});
            table2.AddRow(new string[] {
                        "10026268"});
            table2.AddRow(new string[] {
                        "10034031"});
            table2.AddRow(new string[] {
                        "10030756"});
            table2.AddRow(new string[] {
                        "10062950"});
            table2.AddRow(new string[] {
                        "10026576"});
            table2.AddRow(new string[] {
                        "10056735"});
            table2.AddRow(new string[] {
                        "10026072"});
            table2.AddRow(new string[] {
                        "10040354"});
            table2.AddRow(new string[] {
                        "10025712"});
            table2.AddRow(new string[] {
                        "10004623"});
            table2.AddRow(new string[] {
                        "10030064"});
            table2.AddRow(new string[] {
                        "10025197"});
            table2.AddRow(new string[] {
                        "10030558"});
            table2.AddRow(new string[] {
                        "10004657"});
            table2.AddRow(new string[] {
                        "10021662"});
            table2.AddRow(new string[] {
                        "10046499"});
            table2.AddRow(new string[] {
                        "10042437"});
            table2.AddRow(new string[] {
                        "10027931"});
            table2.AddRow(new string[] {
                        "10063508"});
            table2.AddRow(new string[] {
                        "10004681"});
            table2.AddRow(new string[] {
                        "10049052"});
            table2.AddRow(new string[] {
                        "10041486"});
            table2.AddRow(new string[] {
                        "10038387"});
            table2.AddRow(new string[] {
                        "10057622"});
            table2.AddRow(new string[] {
                        "10004866"});
            table2.AddRow(new string[] {
                        "10041173"});
            table2.AddRow(new string[] {
                        "10038156"});
            table2.AddRow(new string[] {
                        "10044883"});
            table2.AddRow(new string[] {
                        "10041773"});
            table2.AddRow(new string[] {
                        "10062065"});
            table2.AddRow(new string[] {
                        "10061872"});
            table2.AddRow(new string[] {
                        "10004977"});
            table2.AddRow(new string[] {
                        "10056315"});
            table2.AddRow(new string[] {
                        "10025697"});
            table2.AddRow(new string[] {
                        "10028056"});
            table2.AddRow(new string[] {
                        "10063535"});
            table2.AddRow(new string[] {
                        "10056831"});
            table2.AddRow(new string[] {
                        "10023115"});
            table2.AddRow(new string[] {
                        "10062054"});
            table2.AddRow(new string[] {
                        "10062061"});
            table2.AddRow(new string[] {
                        "10005072"});
            table2.AddRow(new string[] {
                        "10062159"});
            table2.AddRow(new string[] {
                        "10024054"});
            table2.AddRow(new string[] {
                        "10037894"});
            table2.AddRow(new string[] {
                        "10040417"});
            table2.AddRow(new string[] {
                        "10054451"});
            table2.AddRow(new string[] {
                        "10036096"});
            table2.AddRow(new string[] {
                        "10005127"});
            table2.AddRow(new string[] {
                        "10063554"});
            table2.AddRow(new string[] {
                        "10053902"});
            table2.AddRow(new string[] {
                        "10000239"});
            table2.AddRow(new string[] {
                        "10035735"});
            table2.AddRow(new string[] {
                        "10054804"});
            table2.AddRow(new string[] {
                        "10021842"});
            table2.AddRow(new string[] {
                        "10044419"});
            table2.AddRow(new string[] {
                        "10043841"});
            table2.AddRow(new string[] {
                        "10021391"});
            table2.AddRow(new string[] {
                        "10046354"});
            table2.AddRow(new string[] {
                        "10028207"});
            table2.AddRow(new string[] {
                        "10063561"});
            table2.AddRow(new string[] {
                        "10062058"});
            table2.AddRow(new string[] {
                        "10043577"});
            table2.AddRow(new string[] {
                        "10036134"});
            table2.AddRow(new string[] {
                        "10043683"});
            table2.AddRow(new string[] {
                        "10010958"});
            table2.AddRow(new string[] {
                        "10032422"});
            table2.AddRow(new string[] {
                        "10019105"});
            table2.AddRow(new string[] {
                        "10062073"});
            table2.AddRow(new string[] {
                        "10036345"});
            table2.AddRow(new string[] {
                        "10005389"});
            table2.AddRow(new string[] {
                        "10048229"});
            table2.AddRow(new string[] {
                        "10023871"});
            table2.AddRow(new string[] {
                        "10036240"});
            table2.AddRow(new string[] {
                        "10061799"});
            table2.AddRow(new string[] {
                        "10031464"});
            table2.AddRow(new string[] {
                        "10024815"});
            table2.AddRow(new string[] {
                        "10003990"});
            table2.AddRow(new string[] {
                        "10054802"});
            table2.AddRow(new string[] {
                        "10044687"});
            table2.AddRow(new string[] {
                        "10005583"});
            table2.AddRow(new string[] {
                        "10005586"});
            table2.AddRow(new string[] {
                        "10023808"});
            table2.AddRow(new string[] {
                        "10033511"});
            table2.AddRow(new string[] {
                        "10062987"});
            table2.AddRow(new string[] {
                        "10033543"});
            table2.AddRow(new string[] {
                        "10056296"});
            table2.AddRow(new string[] {
                        "10062562"});
            table2.AddRow(new string[] {
                        "10030520"});
            table2.AddRow(new string[] {
                        "10063453"});
            table2.AddRow(new string[] {
                        "10034300"});
            table2.AddRow(new string[] {
                        "10063519"});
            table2.AddRow(new string[] {
                        "10027642"});
            table2.AddRow(new string[] {
                        "10023042"});
            table2.AddRow(new string[] {
                        "10019711"});
            table2.AddRow(new string[] {
                        "10062041"});
            table2.AddRow(new string[] {
                        "10035469"});
            table2.AddRow(new string[] {
                        "10005928"});
            table2.AddRow(new string[] {
                        "10005946"});
            table2.AddRow(new string[] {
                        "10023516"});
            table2.AddRow(new string[] {
                        "10005513"});
            table2.AddRow(new string[] {
                        "10053529"});
            table2.AddRow(new string[] {
                        "10006020"});
            table2.AddRow(new string[] {
                        "10042132"});
            table2.AddRow(new string[] {
                        "10061495"});
            table2.AddRow(new string[] {
                        "10036350"});
            table2.AddRow(new string[] {
                        "10008007"});
            table2.AddRow(new string[] {
                        "10006268"});
            table2.AddRow(new string[] {
                        "10030811"});
            table2.AddRow(new string[] {
                        "10010134"});
            table2.AddRow(new string[] {
                        "10009439"});
            table2.AddRow(new string[] {
                        "10031338"});
            table2.AddRow(new string[] {
                        "10019839"});
            table2.AddRow(new string[] {
                        "10006322"});
            table2.AddRow(new string[] {
                        "10063632"});
            table2.AddRow(new string[] {
                        "10001473"});
            table2.AddRow(new string[] {
                        "10061604"});
            table2.AddRow(new string[] {
                        "10006438"});
            table2.AddRow(new string[] {
                        "10023992"});
            table2.AddRow(new string[] {
                        "10004000"});
            table2.AddRow(new string[] {
                        "10040476"});
            table2.AddRow(new string[] {
                        "10063477"});
            table2.AddRow(new string[] {
                        "10063196"});
            table2.AddRow(new string[] {
                        "10047671"});
            table2.AddRow(new string[] {
                        "10006495"});
            table2.AddRow(new string[] {
                        "10041124"});
            table2.AddRow(new string[] {
                        "10036956"});
            table2.AddRow(new string[] {
                        "10006517"});
            table2.AddRow(new string[] {
                        "10049106"});
            table2.AddRow(new string[] {
                        "10052690"});
            table2.AddRow(new string[] {
                        "10009095"});
            table2.AddRow(new string[] {
                        "10006574"});
            table2.AddRow(new string[] {
                        "10031276"});
            table2.AddRow(new string[] {
                        "10031825"});
            table2.AddRow(new string[] {
                        "10043120"});
            table2.AddRow(new string[] {
                        "10061461"});
            table2.AddRow(new string[] {
                        "10000690"});
            table2.AddRow(new string[] {
                        "10001695"});
            table2.AddRow(new string[] {
                        "10030255"});
            table2.AddRow(new string[] {
                        "10026054"});
            table2.AddRow(new string[] {
                        "10009072"});
            table2.AddRow(new string[] {
                        "10063318"});
            table2.AddRow(new string[] {
                        "10030656"});
            table2.AddRow(new string[] {
                        "10019935"});
            table2.AddRow(new string[] {
                        "10058059"});
            table2.AddRow(new string[] {
                        "10061491"});
            table2.AddRow(new string[] {
                        "10052938"});
            table2.AddRow(new string[] {
                        "10061968"});
            table2.AddRow(new string[] {
                        "10032280"});
            table2.AddRow(new string[] {
                        "10061098"});
            table2.AddRow(new string[] {
                        "10058228"});
            table2.AddRow(new string[] {
                        "10039140"});
            table2.AddRow(new string[] {
                        "10063943"});
            table2.AddRow(new string[] {
                        "10005545"});
            table2.AddRow(new string[] {
                        "10007779"});
            table2.AddRow(new string[] {
                        "10029308"});
            table2.AddRow(new string[] {
                        "10032402"});
            table2.AddRow(new string[] {
                        "10006841"});
            table2.AddRow(new string[] {
                        "10007785"});
            table2.AddRow(new string[] {
                        "10039956"});
            table2.AddRow(new string[] {
                        "10036868"});
            table2.AddRow(new string[] {
                        "10006907"});
            table2.AddRow(new string[] {
                        "10063506"});
            table2.AddRow(new string[] {
                        "10027651"});
            table2.AddRow(new string[] {
                        "10023210"});
            table2.AddRow(new string[] {
                        "10057042"});
            table2.AddRow(new string[] {
                        "10027770"});
            table2.AddRow(new string[] {
                        "10007015"});
            table2.AddRow(new string[] {
                        "10048848"});
            table2.AddRow(new string[] {
                        "10055341"});
            table2.AddRow(new string[] {
                        "10007031"});
            table2.AddRow(new string[] {
                        "10039242"});
            table2.AddRow(new string[] {
                        "10004123"});
            table2.AddRow(new string[] {
                        "10054584"});
            table2.AddRow(new string[] {
                        "10007097"});
            table2.AddRow(new string[] {
                        "10042737"});
            table2.AddRow(new string[] {
                        "10047502"});
            table2.AddRow(new string[] {
                        "10043146"});
            table2.AddRow(new string[] {
                        "10043409"});
            table2.AddRow(new string[] {
                        "10040227"});
            table2.AddRow(new string[] {
                        "10049616"});
            table2.AddRow(new string[] {
                        "10063534"});
            table2.AddRow(new string[] {
                        "10019736"});
            table2.AddRow(new string[] {
                        "10029097"});
            table2.AddRow(new string[] {
                        "10007154"});
            table2.AddRow(new string[] {
                        "10007801"});
            table2.AddRow(new string[] {
                        "10007158"});
            table2.AddRow(new string[] {
                        "10007805"});
            table2.AddRow(new string[] {
                        "10003614"});
            table2.AddRow(new string[] {
                        "10007139"});
            table2.AddRow(new string[] {
                        "10061440"});
            table2.AddRow(new string[] {
                        "10038228"});
            table2.AddRow(new string[] {
                        "10027449"});
            table2.AddRow(new string[] {
                        "10038140"});
            table2.AddRow(new string[] {
                        "10062800"});
            table2.AddRow(new string[] {
                        "10062470"});
            table2.AddRow(new string[] {
                        "10030462"});
            table2.AddRow(new string[] {
                        "10007289"});
            table2.AddRow(new string[] {
                        "10007322"});
            table2.AddRow(new string[] {
                        "10029843"});
            table2.AddRow(new string[] {
                        "10008883"});
            table2.AddRow(new string[] {
                        "10029829"});
            table2.AddRow(new string[] {
                        "10007396"});
            table2.AddRow(new string[] {
                        "10007419"});
            table2.AddRow(new string[] {
                        "10041501"});
            table2.AddRow(new string[] {
                        "10001464"});
            table2.AddRow(new string[] {
                        "10057338"});
            table2.AddRow(new string[] {
                        "10003256"});
            table2.AddRow(new string[] {
                        "10026128"});
            table2.AddRow(new string[] {
                        "10055902"});
            table2.AddRow(new string[] {
                        "10063456"});
            table2.AddRow(new string[] {
                        "10007527"});
            table2.AddRow(new string[] {
                        "10062121"});
            table2.AddRow(new string[] {
                        "10061883"});
            table2.AddRow(new string[] {
                        "10045837"});
            table2.AddRow(new string[] {
                        "10007623"});
            table2.AddRow(new string[] {
                        "10027269"});
            table2.AddRow(new string[] {
                        "10007643"});
            table2.AddRow(new string[] {
                        "10008699"});
            table2.AddRow(new string[] {
                        "10052724"});
            table2.AddRow(new string[] {
                        "10004370"});
            table2.AddRow(new string[] {
                        "10054860"});
            table2.AddRow(new string[] {
                        "10063530"});
#line 31
testRunner.And("csv file should contain following information", ((string)(null)), table2, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Roatp Register csv file should not contain below Ukprn")]
        public virtual void RoatpRegisterCsvFileShouldNotContainBelowUkprn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Roatp Register csv file should not contain below Ukprn", ((string[])(null)));
#line 570
this.ScenarioSetup(scenarioInfo);
#line 571
testRunner.Given("I can open roatp website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 572
testRunner.When("I request for SFA Roatp csv file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 573
testRunner.Then("I should have a csv file with more than 5 Kb contents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "UKPRN"});
            table3.AddRow(new string[] {
                        "10001457"});
            table3.AddRow(new string[] {
                        "10011332"});
            table3.AddRow(new string[] {
                        "10058010"});
            table3.AddRow(new string[] {
                        "10007407"});
            table3.AddRow(new string[] {
                        "10005410"});
            table3.AddRow(new string[] {
                        "10001196"});
#line 574
testRunner.And("csv file should not contain following information", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Roatp Register csv file should have right no of Providers")]
        public virtual void RoatpRegisterCsvFileShouldHaveRightNoOfProviders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Roatp Register csv file should have right no of Providers", ((string[])(null)));
#line 584
this.ScenarioSetup(scenarioInfo);
#line 585
testRunner.Given("I can open roatp website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 586
testRunner.When("I request for SFA Roatp csv file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 587
testRunner.Then("I should have a csv file with more than 5 Kb contents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 588
testRunner.And("I should have total 2215 Providers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
